// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct connection: Neon's pooled endpoint cannot hold the
    // advisory lock Prisma takes while applying them. The running app keeps using the
    // pooled DATABASE_URL. `neon link` writes DATABASE_URL_UNPOOLED itself, so this
    // stays in step with the CLI; locally neither is set and it falls through.
    url:
      process.env["DATABASE_URL_UNPOOLED"] ??
      process.env["DIRECT_URL"] ??
      process.env["DATABASE_URL"],
  },
});
